name: Asset Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  can-build-assets:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm install
    - name: Build Assets
      run: npm run prod
